"""add announcements and notification fields

Revision ID: 417cc85441cf
Revises: 92270b4407e0
Create Date: 2026-03-02 18:19:18.102325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417cc85441cf'
down_revision: Union[str, Sequence[str], None] = '92270b4407e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('file_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'file_url')
    op.drop_column('notifications', 'entity_type')
    # ### end Alembic commands ###
