"""add_drive_tokens_to_user

Revision ID: eecd114a9e7d
Revises: 1f293a2bef61
Create Date: 2026-03-02 04:56:27.175166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecd114a9e7d'
down_revision: Union[str, Sequence[str], None] = '1f293a2bef61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('drive_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('drive_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('drive_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'drive_token_expiry')
    op.drop_column('users', 'drive_refresh_token')
    op.drop_column('users', 'drive_access_token')
    # ### end Alembic commands ###
